TASK_OBJS = output/myOS/kernel/task/task.o \
			output/myOS/kernel/task/taskQueue.o \
			output/myOS/kernel/task/scheduler.o \
			output/myOS/kernel/task/taskPara.o \
			output/myOS/kernel/task/FCFS.o \
			output/myOS/kernel/task/PRI.o \
			output/myOS/kernel/task/RR.o